window.HomestayUserDB = (() => {
    const DB_NAME = 'HomestayUserDB', VERSION = 3;
    let ready;
    function open() {
        if (ready) return ready;
        ready = new Promise((resolve, reject) => {
            const request = indexedDB.open(DB_NAME, VERSION);
            request.onupgradeneeded = event => {
                const db = event.target.result;
                if (!db.objectStoreNames.contains('favorites')) db.createObjectStore('favorites', { keyPath: 'id' });
                if (!db.objectStoreNames.contains('serviceBookings')) db.createObjectStore('serviceBookings', { keyPath: 'id' });
                if (!db.objectStoreNames.contains('homestays')) db.createObjectStore('homestays', { keyPath: 'id' });
                if (!db.objectStoreNames.contains('selectedHomestay')) db.createObjectStore('selectedHomestay', { keyPath: 'id' });
            };
            request.onsuccess = event => resolve(event.target.result);
            request.onerror = () => reject(request.error);
        });
        return ready;
    }
    async function all(store) { const db = await open(); return new Promise((resolve, reject) => { const r = db.transaction(store).objectStore(store).getAll(); r.onsuccess = () => resolve(r.result); r.onerror = () => reject(r.error); }); }
    async function put(store, item) { const db = await open(); return new Promise((resolve, reject) => { const r = db.transaction(store, 'readwrite').objectStore(store).put(item); r.onsuccess = () => resolve(r.result); r.onerror = () => reject(r.error); }); }
    async function remove(store, id) { const db = await open(); return new Promise((resolve, reject) => { const r = db.transaction(store, 'readwrite').objectStore(store).delete(id); r.onsuccess = resolve; r.onerror = () => reject(r.error); }); }
    async function ensureSearchData() {
        const existing = await all('homestays');
        if (existing.length) {
            const proudStay = existing.find(item => item.id === 'hs-hoian-river');
            if (proudStay && !Array.isArray(proudStay.travelGroups)) proudStay.travelGroups = [];
            if (proudStay && !proudStay.travelGroups.includes('Travel Proud (thân thiện với cộng đồng LGBTQ+)')) {
                proudStay.travelGroups.push('Travel Proud (thân thiện với cộng đồng LGBTQ+)');
                await put('homestays', proudStay);
            }
            return;
        }
        const homestays = [
            { id: 'hs-maichau-moc', name: 'Nhà Sàn Mộc', location: 'Mai Châu, Hòa Bình', address: 'Bản Lác, Mai Châu, Hòa Bình', description: 'Nhà sàn truyền thống giữa thung lũng, phù hợp cho kỳ nghỉ yên tĩnh và trải nghiệm văn hóa bản địa.', image: '../images/categories/4_nha_que_truyen_thong.jpg', pricePerNight: 650000, maxGuests: 6, rating: 4.8, reviewCount: 42, stars: 4, services: ['Trekking', 'Ẩm thực bản địa', 'Đạp xe bản làng'], roomAmenities: ['Phòng tắm riêng', 'Ban công', 'Quạt máy'], amenities: ['Wi‑Fi miễn phí', 'Bãi đỗ xe', 'Nhà hàng', 'Sân vườn'], travelGroups: ['Gia đình', 'Cặp đôi', 'LGPT'], featured: true },
            { id: 'hs-maichau-cloud', name: 'Mây Trôi Valley Lodge', location: 'Mai Châu, Hòa Bình', address: 'Bản Pom Coọng, Mai Châu, Hòa Bình', description: 'Lodge gỗ ấm cúng, có không gian ngắm núi và phục vụ tour khám phá bản làng.', image: '../images/categories/7_thien_nhien_sinh_thai.jpg', pricePerNight: 920000, maxGuests: 4, rating: 4.9, reviewCount: 58, stars: 4, services: ['Tour bản làng', 'Ngâm chân thảo mộc'], roomAmenities: ['Máy điều hòa', 'Phòng tắm riêng', 'Ban công'], amenities: ['Wi‑Fi miễn phí', 'Bữa sáng', 'Bãi đỗ xe'], travelGroups: ['Cặp đôi', 'Gia đình'], featured: true },
            { id: 'hs-dalat-pine', name: 'Pine Hill Retreat', location: 'Đà Lạt, Lâm Đồng', address: 'Đường Ankroet, Đà Lạt, Lâm Đồng', description: 'Không gian nhà gỗ bên đồi thông, có bếp chung và khu đốt lửa trại.', image: '../images/categories/10_kham_pha_lang_que.jpg', pricePerNight: 780000, maxGuests: 8, rating: 4.7, reviewCount: 35, stars: 4, services: ['Đốt lửa trại', 'Tour săn mây'], roomAmenities: ['Bếp nhỏ', 'Nước nóng', 'Ban công'], amenities: ['Wi‑Fi miễn phí', 'Bãi đỗ xe', 'Khu BBQ'], travelGroups: ['Nhóm bạn', 'Gia đình', 'Cho phép mang theo vật nuôi'], featured: false },
            { id: 'hs-hoian-river', name: 'Riverside Garden Homestay', location: 'Hội An, Quảng Nam', address: 'Cẩm Thanh, Hội An, Quảng Nam', description: 'Homestay ven sông với vườn xanh, gần làng rau Trà Quế và phố cổ Hội An.', image: '../images/categories/3_song_nuoc.jpg', pricePerNight: 540000, maxGuests: 3, rating: 4.6, reviewCount: 27, stars: 3, services: ['Đi thuyền thúng', 'Lớp nấu ăn'], roomAmenities: ['Phòng tắm riêng', 'Máy điều hòa', 'Minibar'], amenities: ['Wi‑Fi miễn phí', 'Xe đạp miễn phí', 'Đưa đón sân bay'], travelGroups: ['Cặp đôi', 'Du lịch một mình', 'Travel Proud (thân thiện với cộng đồng LGBTQ+)'], featured: false },
            { id: 'hs-sapa-farm', name: 'Tả Van Farmstay', location: 'Sa Pa, Lào Cai', address: 'Tả Van, Sa Pa, Lào Cai', description: 'Farmstay mộc mạc với ruộng bậc thang, hoạt động làm nông và trải nghiệm đời sống bản địa.', image: '../images/categories/2_nong_trai.jpg', pricePerNight: 480000, maxGuests: 10, rating: 4.8, reviewCount: 49, stars: 3, services: ['Làm nông', 'Trekking', 'Thuê trang phục dân tộc'], roomAmenities: ['Phòng gia đình', 'Chăn điện', 'Phòng tắm riêng'], amenities: ['Wi‑Fi miễn phí', 'Nhà hàng', 'Bãi đỗ xe'], travelGroups: ['Gia đình', 'Nhóm bạn', 'Khách du lịch ba lô'], featured: true },
            { id: 'hs-dalat-flower', name: 'Mộng Mơ Valley Homestay', location: 'Đà Lạt, Lâm Đồng', address: 'Đường Hùng Vương, Đà Lạt, Lâm Đồng', description: 'Homestay tràn ngập hoa tươi, góc nhìn thung lũng đón bình minh cực đẹp.', image: '../images/categories/10_kham_pha_lang_que.jpg', pricePerNight: 850000, maxGuests: 6, rating: 4.8, reviewCount: 41, stars: 4, services: ['Tiệc BBQ ngoài trời', 'Thuê xe máy'], roomAmenities: ['Máy sưởi', 'Phòng tắm riêng', 'Máy pha cà phê'], amenities: ['Wi‑Fi miễn phí', 'Sân vườn', 'Quầy bar mini'], travelGroups: ['Cặp đôi', 'Nhóm bạn'], featured: false },
            { id: 'hs-sapa-cloud', name: 'Lao Chải Haven Lodge', location: 'Sa Pa, Lào Cai', address: 'Lao Chải, Sa Pa, Lào Cai', description: 'Homestay săn mây tuyệt đẹp, nhìn ra toàn cảnh thung lũng Mường Hoa.', image: '../images/categories/2_nong_trai.jpg', pricePerNight: 620000, maxGuests: 4, rating: 4.9, reviewCount: 63, stars: 4, services: ['Trekking ngắm thung lũng', 'Tắm lá thuốc Dao đỏ'], roomAmenities: ['Ban công ngắm cảnh', 'Máy sưởi', 'Bồn tắm'], amenities: ['Wi‑Fi miễn phí', 'Nhà hàng', 'Bữa sáng miễn phí'], travelGroups: ['Cặp đôi', 'Du lịch trải nghiệm'], featured: true },
            { id: 'hs-ninhbinh-lotus', name: 'Tràng An Eco Homestay', location: 'Ninh Bình', address: 'Tràng An, Hoa Lư, Ninh Bình', description: 'Không gian yên bình bên dòng sông và núi đá vôi trù phú.', image: '../images/categories/3_song_nuoc.jpg', pricePerNight: 520000, maxGuests: 5, rating: 4.7, reviewCount: 38, stars: 3, services: ['Tour chèo thuyền Kayak', 'Câu cá giải trí'], roomAmenities: ['Máy điều hòa', 'Phòng tắm riêng'], amenities: ['Wi‑Fi miễn phí', 'Bãi đỗ xe', 'Cho thuê xe đạp'], travelGroups: ['Gia đình', 'Du lịch một mình'], featured: true },
            { id: 'hs-phuquoc-breeze', name: 'Châu Long Island Homestay', location: 'Phú Quốc, Kiên Giang', address: 'Cửa Dương, Phú Quốc, Kiên Giang', description: 'Bungalow gỗ gần biển, không gian thoáng đãng mát mẻ quanh năm.', image: '../images/categories/7_thien_nhien_sinh_thai.jpg', pricePerNight: 890000, maxGuests: 4, rating: 4.8, reviewCount: 52, stars: 4, services: ['Tour lặn ngắm san hô', 'Đốt lửa trại bờ biển'], roomAmenities: ['Máy điều hòa', 'Minibar', 'Ban công'], amenities: ['Wi‑Fi miễn phí', 'Hồ bơi ngoài trời', 'Đưa đón sân bay'], travelGroups: ['Cặp đôi', 'Gia đình'], featured: true },

            { id: 'hs-dalat-wood-coffee', name: 'Tiệm Cà Phê & Homestay Bình Yên', location: 'Đà Lạt, Lâm Đồng', address: 'Đường Khe Sanh, Phường 10, Đà Lạt, Lâm Đồng', description: 'Căn nhà gỗ view thung lũng đồi thông cực chill, tích hợp tiệm cà phê ngắm hoàng hôn.', image: '../images/categories/10_kham_pha_lang_que.jpg', pricePerNight: 690000, maxGuests: 4, rating: 4.8, reviewCount: 76, stars: 4, services: ['Pha cà phê thủ công', 'Thuê xe máy', 'Chụp ảnh thung lũng'], roomAmenities: ['Máy sưởi', 'Ban công ngắm cảnh', 'Máy pha cà phê'], amenities: ['Wi‑Fi miễn phí', 'Quầy bar', 'Bãi đỗ xe', 'Khu BBQ'], travelGroups: ['Cặp đôi', 'Nhóm bạn', 'Du lịch một mình'], featured: true },
            { id: 'hs-dalat-glass-cloud', name: 'Mây Trắng Glass House', location: 'Đà Lạt, Lâm Đồng', address: 'Đồi Cầu Đất, Phường 11, Đà Lạt, Lâm Đồng', description: 'Thiết kế kính trong suốt nhìn ra biển mây Cầu Đất, điểm săn mây và bình minh lý tưởng.', image: '../images/categories/7_thien_nhien_sinh_thai.jpg', pricePerNight: 1200000, maxGuests: 2, rating: 4.9, reviewCount: 94, stars: 5, services: ['Tour săn mây Cầu Đất', 'Bữa sáng tại phòng', 'Chụp ảnh Polaroid'], roomAmenities: ['Kính toàn cảnh 360', 'Bồn tắm ngâm thảo dược', 'Chăn điện', 'Loa Bluetooth'], amenities: ['Wi‑Fi miễn phí', 'Sân thượng', 'Bãi đỗ xe ô tô'], travelGroups: ['Cặp đôi', 'Hưởng tuần trăng mật'], featured: true },
            { id: 'hs-dalat-vintage-corner', name: 'Góc Nhỏ Vintage Homestay', location: 'Đà Lạt, Lâm Đồng', address: 'Đường Lý Tự Trọng, Phường 2, Đà Lạt, Lâm Đồng', description: 'Nằm gần trung tâm và chợ Đà Lạt, phong cách Retro cổ điển ấm cúng với góc đọc sách xinh xắn.', image: '../images/categories/4_nha_que_truyen_thong.jpg', pricePerNight: 450000, maxGuests: 3, rating: 4.6, reviewCount: 31, stars: 3, services: ['Giặt ủi', 'Gợi ý ẩm thực địa phương', 'Cho thuê xe ga'], roomAmenities: ['Máy điều hòa', 'Phòng tắm riêng', 'Máy sấy tóc'], amenities: ['Wi‑Fi miễn phí', 'Bếp chung', 'Góc đọc sách'], travelGroups: ['Du lịch một mình', 'Nhóm bạn', 'Khách du lịch ba lô'], featured: false },
            { id: 'hs-dalat-glamping-lake', name: 'Rừng Sương Glamping & Cabin', location: 'Đà Lạt, Lâm Đồng', address: 'Đường Hồ Tuyền Lâm, Phường 4, Đà Lạt, Lâm Đồng', description: 'Khu lều Glamping cao cấp kết hợp bungalow bên hồ Tuyền Lâm, không khí trong lành tự nhiên.', image: '../images/categories/7_thien_nhien_sinh_thai.jpg', pricePerNight: 1100000, maxGuests: 4, rating: 4.9, reviewCount: 88, stars: 4, services: ['Chèo SUB Hồ Tuyền Lâm', 'Tiệc nướng BBQ thịt nướng Đà Lạt', 'Đốt lửa trại đêm'], roomAmenities: ['Đệm sưởi', 'Đèn bão decor', 'Phòng tắm riêng khép kín'], amenities: ['Wi‑Fi miễn phí', 'Sân nướng ngoài trời', 'Bãi đỗ xe rộng'], travelGroups: ['Cặp đôi', 'Nhóm bạn', 'Gia đình'], featured: true },
            { id: 'hs-dalat-aframe-house', name: 'Nhà Gỗ A-Frame Tùng Lâm', location: 'Đà Lạt, Lâm Đồng', address: 'Hướng đi Suối Vàng, Phường 7, Đà Lạt, Lâm Đồng', description: 'Căn bungalow mái chữ A xinh xắn nằm ẩn mình giữa vườn hoa cẩm tú cầu và đồi thông.', image: '../images/categories/10_kham_pha_lang_que.jpg', pricePerNight: 820000, maxGuests: 5, rating: 4.7, reviewCount: 45, stars: 4, services: ['Hái dâu tây tại vườn', 'Thuê xe ô tô tự lái', 'Setup tiệc sinh nhật'], roomAmenities: ['Tầng gác xép', 'Bếp nấu nhỏ', 'Nước nóng trung tâm'], amenities: ['Wi‑Fi miễn phí', 'Vườn hoa cẩm tú cầu', 'Sân nướng BBQ'], travelGroups: ['Gia đình', 'Cặp đôi', 'Nhóm bạn'], featured: false },
            { id: 'hs-dalat-valley-villa', name: 'Thung Lũng Hoa Villa & Homestay', location: 'Đà Lạt, Lâm Đồng', address: 'Đường Hoàng Hoa Thám, Phường 10, Đà Lạt, Lâm Đồng', description: 'Villa gia đình nguyên căn có sân vườn rộng, không gian thoáng đãng ngắm trọn thung lũng Đèn lung linh đêm.', image: '../images/categories/10_kham_pha_lang_que.jpg', pricePerNight: 1800000, maxGuests: 12, rating: 4.8, reviewCount: 67, stars: 5, services: ['Nấu ăn theo yêu cầu', 'Setup BBQ sân vườn', 'Đưa đón bến xe/sân bay'], roomAmenities: ['Smart TV', 'Bếp gia đình đầy đủ dụng cụ', 'Ban công rộng', 'Nước nóng'], amenities: ['Wi‑Fi tốc độ cao', 'Bãi đỗ xe 16 chỗ', 'Sân chơi trẻ em', 'Khu nướng BBQ'], travelGroups: ['Gia đình', 'Nhóm bạn'], featured: true },
            { id: 'hs-dalat-boho-nest', name: 'Boho Nest Homestay Đà Lạt', location: 'Đà Lạt, Lâm Đồng', address: 'Đường Yersin, Phường 9, Đà Lạt, Lâm Đồng', description: 'Phong cách Bohemian nghệ thuật, đầy màu sắc với nhiều góc check-in sống ảo cực độc đáo.', image: '../images/categories/4_nha_que_truyen_thong.jpg', pricePerNight: 550000, maxGuests: 2, rating: 4.7, reviewCount: 53, stars: 3, services: ['Workshop vẽ tranh', 'Thuê trang phục Bohemian', 'Cho thuê xe máy'], roomAmenities: ['Gương soi toàn thân', 'Máy sấy tóc', 'Loa nghe nhạc vintage'], amenities: ['Wi‑Fi miễn phí', 'Bếp dùng chung', 'Cà phê & trà miễn phí'], travelGroups: ['Cặp đôi', 'Nhóm bạn', 'Travel Proud (thân thiện với cộng đồng LGBTQ+)'], featured: false }
        ];
        await Promise.all(homestays.map(item => put('homestays', item)));
    }
    return { all, put, remove, ensureSearchData };
})();
